### ISSUE TITLE
NoMethodError: undefined method `new' for Fog::Storage:Module with fog > 1.26

### ISSUE THREAD

**Issue by waynehoover** [rumblelabs/asset_sync#303]
I'm getting the below error when trying to do `rake assets:precompile` Using fog 1.29

Update: If I lock fog to version 1.26 it works. 

```
bundle exec rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
** Invoke assets:sync (first_time)
** Invoke assets:environment
** Execute assets:sync
rake aborted!
NoMethodError: undefined method `new' for Fog::Storage:Module
./asset_sync-1.1.0/lib/asset_sync/storage.rb:15:in `connection'
./asset_sync-1.1.0/lib/asset_sync/storage.rb:20:in `bucket'
./asset_sync-1.1.0/lib/asset_sync/storage.rb:99:in `get_remote_files'
./asset_sync-1.1.0/lib/asset_sync/storage.rb:211:in `upload_files'
./asset_sync-1.1.0/lib/asset_sync/storage.rb:233:in `sync'
./asset_sync-1.1.0/lib/asset_sync/asset_sync.rb:29:in `block in sync'
./asset_sync-1.1.0/lib/asset_sync/asset_sync.rb:51:in `call'
./asset_sync-1.1.0/lib/asset_sync/asset_sync.rb:51:in `with_config'
./asset_sync-1.1.0/lib/asset_sync/asset_sync.rb:28:in `sync'
./asset_sync-1.1.0/lib/tasks/asset_sync.rake:5:in `block (2 levels) in <top (required)>'
...
Tasks: TOP => assets:sync
```

**Comment by bcavileer** [comment]
Are you perhaps using the Optimized Fog Loading? https://github.com/rumblelabs/asset_sync#optimized-fog-loading
```
gem "fog", "~>1.20", require: "fog/aws/storage"
```

I saw a similar issue, and I fixed it by removing the require
try without the ```, require: "fog/aws/storage"```
just ```gem "fog", "~> 1.20"```


Just for reference this was my error:
```
rake aborted!
NameError: uninitialized constant Fog::Service
gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:3:in `<module:Storage>'
gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:2:in `<module:Fog>'
gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:1:in `<top (required)>'
gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
/config/application.rb:7:in `<top (required)>'
/Rakefile:5:in `require'
/Rakefile:5:in `<top (required)>'
bin/ruby_executable_hooks:15:in `eval'
bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by waynehoover** [comment]
Yes, thank you, this was because of the optimized fog loading I was doing.
